gitlab-runnner: Restart service after upgrading
majkinetor/au-packages pull request #213
Opened 2022-04-25 10:40 UTC by cmorty

The quick-fix is to enable `useRememberedArgumentsForUpgrades`, but restarting the service is probably the better solution.

2022-04-25 14:23 UTC, majkinetor commented
> The quick fix is to enable useRememberedArgumentsForUpgrades

Is it though ? That feature is buggy and just month ago it uses saved parameters from one package and applies it to another. Since I used standard package parameters it finished installing several tools into the same folder ?! Its known bug for a long time.

2022-04-25 14:24 UTC, majkinetor requested changes

2022-04-25 14:24 UTC, majkinetor commented on gitlab-runner/tools/chocolateyInstall.ps1
> +Write-Host "Starting service"
You didn't check if service was actually started. What if I want it manual ?

2022-04-25 14:41 UTC, cmorty commented on gitlab-runner/tools/chocolateyInstall.ps1
> +Write-Host "Starting service"
> > The quick fix is to enable useRememberedArgumentsForUpgrades
> 
> Is it though ? 

Worked for me, but I didn't like it. Thus this MR. ;) Currently it kills the service on each update, which is just as bad. ;-) (I use choco-upgrade-all-at). Thus you want a check, whether the service was running before, right? I'll do my best (pwsh is somewhat a foreign language to me. ;) ).

2022-04-26 07:39 UTC, majkinetor commented on gitlab-runner/tools/chocolateyInstall.ps1
> +Write-Host "Starting service"
>  Currently it kills the service on each update, which is just as bad.

Why? What problems do you have?

Stopping service seems equally bad. It depends on what service is doing at the moment. If it is in the middle of deployment, stopping or killing it will probably result in the same thing. 

The safe thing to do would probably be to a) block service for accepting new jobs b) wait for it to finish current jobs c) update it, and each step could be controllable via parameter. This could probably be done by scanning runner logs but IMO is overkill.

2022-04-27 06:22 UTC, cmorty commented on gitlab-runner/tools/chocolateyInstall.ps1
> +Write-Host "Starting service"
> > Currently it kills the service on each update, which is just as bad.
> 
> Why? What problems do you have?

I use `choco-upgrade-all-at` to keep the server up to date. As the install-script stops the service before updating, the service got stopped, but never started again.

> 
> Stopping service seems equally bad. It depends on what service is doing at the moment. If it is in the middle of deployment, stopping or killing it will probably result in the same thing.

Yes, but that what the install script already does. So no regression here. Gitlab-Runner doesn't really support graceful shutdown - at least the last time I checked. I can double-check. But that would be a new MR.

Are you happy with my latest version? 

* The service is stopped before installing (old behavior)
* The service is started after installing, if it was running before (new behavior)
*  `/Service`: 
  * The service gets started on a new install (old behavior)
  * If the service existed before, there is no special handling (old: the service was started)

2022-04-27 06:43 UTC, majkinetor commented on gitlab-runner/tools/chocolateyInstall.ps1
> +Write-Host "Starting service"
Yeah, that is OK.

Thanks.

2022-04-27 06:43 UTC, merged